"""initial_schema

Revision ID: a56f149cc9ba
Revises: 
Create Date: 2026-06-21 19:11:55.975151

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = 'a56f149cc9ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
